apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: local-storage
  keystone:
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-keystone:current-tripleo
      databaseInstance: openstack
      secret: osp-secret
  mariadb:
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo
      storageRequest: 500M
  rabbitmq:
    template:
      replicas: 1
      #resources:
      #  requests:
      #    cpu: 500m
      #    memory: 1Gi
      #  limits:
      #    cpu: 800m
      #    memory: 1Gi
  placement:
    enabled: false
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-placement-api:current-tripleo
      databaseInstance: openstack
      secret: osp-secret
  glance:
    template:
      serviceUser: glance
      databaseInstance: openstack
      databaseUser: glance
      secret: osp-secret
      storageClass: ""
      storageRequest: 1G
      customServiceConfig: |
        [DEFAULT]
        debug = true
      glanceAPIInternal:
        debug:
          service: false
        preserveJobs: false
        replicas: 1
      glanceAPIExternal:
        debug:
          service: false
        preserveJobs: false
        replicas: 1
      cephBackend:
        cephFsid: 5fe62cc7-0392-4a32-8466-081ce0ea970f
        cephMons: 192.168.130.1
        cephClientKey: AQBCtBhj0gM6FRAACq4EGHK6qYqRBSbw4zFavg==
        cephUser: admin
        cephPools:
          glance:
            name: images
  cinder:
    enabled: true
    template:
      rabbitMqClusterName: rabbitmq
      customServiceConfig: |
        [DEFAULT]
        debug = true
      databaseInstance: openstack
      databaseUser: cinder
      cinderAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-api:current-tripleo
        debug:
          initContainer: false
          service: false
      cinderScheduler:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-scheduler:current-tripleo
        debug:
          initContainer: false
          service: false
      cinderBackup:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-backup:current-tripleo
        customServiceConfig: |
          [DEFAULT]
          backup_driver = cinder.backup.drivers.ceph.CephBackupDriver
          backup_ceph_pool = backups
          backup_ceph_user = admin
        debug:
          initContainer: false
          service: false
      secret: osp-secret
      cinderVolumes:
        ceph:
          containerImage: quay.io/tripleozedcentos9/openstack-cinder-volume:current-tripleo
          replicas: 1
          customServiceConfig: |
            [DEFAULT]
            enabled_backends=ceph
          debug:
            initContainer: false
            service: false
      cephBackend:
        cephFsid: 5fe62cc7-0392-4a32-8466-081ce0ea970f
        cephMons: 192.168.130.1
        cephClientKey: AQBCtBhj0gM6FRAACq4EGHK6qYqRBSbw4zFavg==
        cephUser: admin
        cephPools:
          cinder:
            name: volumes
          cinder_backup:
            name: backup
